apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-runner-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-runner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-runner-role
subjects:
- kind: ServiceAccount
  name: argo-runner
